server:
  port: 5555

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # set false for production
  datasource:
    url: ${POSTGRES_URL:}
    username: ${POSTGRES_USERNAME:}
    password: ${POSTGRES_PASSWORD:}
    hikari:
      minimumIdle: 5
      maximumPoolSize: 40
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
      poolName: Telegram

management:
  endpoints:
    web:
      exposure:
        include: '*'

telegrambot:
  botUsername: ${TELEGRAM_BOT_USERNAME:}
  botToken: ${TELEGRAM_BOT_TOKEN:}
  webHookPath: ${TELEGRAM_WEB_HOOK_PATH:}

ai:
  token: ${GPT_TOKEN:}
